# -*- coding: utf-8 -*-
"""用 Python 标准库生成一封可离线打开的寒露动态情书。

运行：python 寒露情书.py
自定义：python 寒露情书.py --name 陌陌 --sender 小周 --no-open
浏览器负责播放动画，Python 负责生成完整、可分享的单文件页面。
"""
import argparse
import base64
import json
import webbrowser
from pathlib import Path


HTML = r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#ffe7ed">
<title>寒露微凉，你在心上</title>
<style>
:root{--ink:#6d2847;--muted:#995e73;--rose:#ce4879;--gold:#b88652;--paper:rgba(255,250,247,.87);--line:rgba(181,86,117,.19)}
*{box-sizing:border-box}html{min-height:100%;background:#ffe7ed}body{margin:0;color:var(--ink);font-family:"Microsoft YaHei","PingFang SC",sans-serif;overflow-x:hidden;background:radial-gradient(ellipse at 12% 8%,#fff7dc 0,transparent 42%),radial-gradient(ellipse at 90% 85%,#f8bad4 0,transparent 42%),linear-gradient(125deg,#ffe6ea,#ffedf3 45%,#f5d9ec);min-height:100svh}
button{font:inherit;cursor:pointer;-webkit-tap-highlight-color:transparent}button:focus-visible{outline:3px solid #b34275;outline-offset:5px}button:disabled{cursor:default}button,a{touch-action:manipulation}a{color:var(--rose)}
.twinkle{position:absolute;color:#bd9466;font-size:12px;animation:twinkle 4s ease-in-out infinite;opacity:.5}.dewdrop{position:absolute;width:7px;height:10px;border-radius:70% 30% 70% 70%;transform:rotate(-35deg);background:linear-gradient(135deg,#fff,#e2b4d577);box-shadow:0 0 10px #fff;animation:twinkle 5s infinite}@keyframes twinkle{0%,100%{opacity:.15}50%{opacity:.75;filter:drop-shadow(0 0 4px #fff)}}.ambient{position:fixed;inset:0;pointer-events:none;overflow:hidden}.orb{position:absolute;width:40vw;height:40vw;min-width:240px;min-height:240px;border-radius:50%;filter:blur(65px);opacity:.37;background:#ffbcdb;animation:drift 15s ease-in-out infinite alternate}.orb:nth-child(2){right:-10%;top:20%;background:#fff8d6;animation-delay:-7s}.orb:nth-child(3){left:15%;bottom:-25%;background:#edb9e2;animation-delay:-4s}
@keyframes drift{to{transform:translate(50px,-45px) scale(1.17)}}
#sky,#spark{position:fixed;inset:0;width:100%;height:100%;pointer-events:none}#sky{z-index:1}#spark{z-index:12}
.frame{position:fixed;inset:18px;border:1px solid rgba(176,115,90,.23);border-radius:22px;pointer-events:none;z-index:2}.frame:before,.frame:after{content:'✦';position:absolute;color:#bd8b66;font-size:21px;top:-13px;background:#ffedf1;padding:0 10px}.frame:before{left:30px}.frame:after{right:30px}
header{position:relative;z-index:4;width:100%;max-width:1140px;margin:auto;padding:38px 48px 16px;display:flex;align-items:center;justify-content:space-between;gap:16px}.brand{font-size:12px;letter-spacing:.2em;color:var(--muted);line-height:1.9}.brand strong{display:block;font-family:Georgia,serif;letter-spacing:.22em;font-weight:normal;color:var(--ink);font-size:17px}.tools{display:flex;gap:8px;flex-shrink:0}.tool{white-space:nowrap;border:1px solid var(--line);background:#fff7f8b3;color:var(--ink);border-radius:40px;font-size:12px;padding:10px 14px}.tool:hover{background:#fff}.hidden{display:none!important}
main{position:relative;z-index:3;max-width:1060px;padding:20px 40px 35px;margin:auto}.scene{display:none}.scene.active{display:block;animation:enter .9s both}@keyframes enter{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}
.eyebrow{font-size:11px;letter-spacing:.32em;color:var(--rose);text-transform:uppercase}.title{font-family:"STKaiti","KaiTi","Songti SC","SimSun",serif;font-weight:normal;font-size:clamp(42px,6vw,68px);margin:14px 0 20px;line-height:1.24;letter-spacing:.08em}.subtitle{font-size:15px;color:var(--muted);line-height:2.1}.center{text-align:center}.primary{position:relative;border:1px solid #b84773;background:linear-gradient(135deg,#d96491,#b83f72);color:#fff8fb;padding:14px 28px;border-radius:50px;box-shadow:0 8px 28px #c74c7533;letter-spacing:.08em;transition:transform .2s,box-shadow .2s}.primary:hover{transform:translateY(-3px);box-shadow:0 12px 30px #c74c7555}.ghost{color:var(--rose);background:#fff6f9b0;border:1px solid #d49ab0;padding:12px 22px;border-radius:40px}.actions{display:flex;align-items:center;justify-content:center;gap:12px;flex-wrap:wrap;margin-top:26px}.note{font-size:11px;color:var(--muted);line-height:1.8}.serif{font-family:"STKaiti","KaiTi","Songti SC","SimSun",serif}
.cover{max-width:850px;margin:0 auto;text-align:center;padding:24px 0 8px}.cover .title{margin-bottom:12px}.envelope{position:relative;width:320px;height:213px;margin:46px auto 40px;filter:drop-shadow(0 20px 24px #ac47772b);animation:float 5s ease-in-out infinite}.envelope svg{width:100%;height:100%;overflow:visible}.seal{transform-origin:160px 125px;animation:pulse 2s infinite}.cover.opening .envelope{animation:send 1s forwards}.cover.opening .seal{animation:none}.stamp{font-size:12px;letter-spacing:2px;color:#b54f7a}.cover-tip{margin-top:17px}
@keyframes float{50%{transform:translateY(-12px) rotate(1deg)}}@keyframes pulse{50%{transform:scale(1.1)}}@keyframes send{to{transform:translateY(-90px) rotate(-8deg) scale(1.15);opacity:0}}
.paper{position:relative;background:var(--paper);border:1px solid #fffbf9;border-radius:24px;padding:42px;box-shadow:0 20px 75px #a6537b14,inset 0 0 0 7px #fff8f633;overflow:hidden}.paper:before{content:'';position:absolute;inset:12px;border:1px solid var(--line);border-radius:15px;pointer-events:none}.hero{display:grid;grid-template-columns:1fr 1fr;min-height:470px;align-items:center;gap:24px}.hero-copy{position:relative;z-index:2;padding-left:8px}.solar-title{font-family:"STKaiti","KaiTi","Songti SC","SimSun",serif;font-weight:normal;font-size:clamp(78px,11vw,128px);letter-spacing:.13em;margin:14px 0;color:#983f62;line-height:1.15}.hero-copy h2{font-weight:normal;font-size:24px;line-height:1.7;margin:18px 0}.divider{width:50px;height:1px;background:#c39570;margin:24px 0}.illustration{position:relative;height:360px;display:flex;align-items:center;justify-content:center}.moon{position:absolute;width:265px;height:265px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fffbea,#ffe6d8 60%,#f5d0d8);box-shadow:0 0 70px #ffcfd877}.moon:before{content:'';position:absolute;inset:12px;border:1px solid #fff9ed;border-radius:50%}.autumn-art{position:relative;width:100%;max-width:360px;height:100%;animation:float 9s infinite}.tiny-heart{position:absolute;top:10%;right:12%;font-size:27px;color:#cf6488;animation:float 4s infinite}.handnote{position:absolute;bottom:7px;right:25px;font-size:16px;transform:rotate(-7deg);color:#b57864}.dedication{margin-top:25px;font-size:12px;letter-spacing:.12em;color:var(--muted)}
.section-head{text-align:center;margin:8px 0 30px}.section-head .title{font-size:clamp(30px,4vw,43px)}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:17px}.season-card{background:var(--paper);border:1px solid #fff;border-radius:20px;padding:24px 22px;box-shadow:0 14px 40px #ab557515;animation:cardin .8s both}.season-card:nth-child(2){animation-delay:.22s}.season-card:nth-child(3){animation-delay:.44s}@keyframes cardin{from{opacity:0;transform:rotateY(40deg) translateY(20px)}to{opacity:1;transform:none}}.card-art{height:125px;display:flex;align-items:center;justify-content:center;background:radial-gradient(ellipse,#ffe0e99c,transparent 70%);margin-bottom:15px}.card-art svg{width:130px;height:120px}.card-num{font-family:Georgia,serif;color:#bb8267;font-size:12px;letter-spacing:.15em}.season-card h3{font-size:24px;font-weight:normal;margin:14px 0}.season-card p{font-size:13px;line-height:2;color:var(--muted);margin:0}.season-card .romance{border-top:1px solid var(--line);padding-top:17px;margin-top:17px;color:var(--ink);font-size:14px}.source{text-align:center;font-size:10px;color:var(--muted);margin:20px 0 0;line-height:1.7}.flower-button{background:none;border:none;padding:0;border-radius:50%;transition:transform .5s}.flower-button:hover{transform:rotate(15deg)}
.letter{max-width:750px;margin:0 auto;padding:42px 55px 34px}.letter-head{display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid var(--line);padding-bottom:20px;margin-bottom:23px}.letter-head .eyebrow{letter-spacing:.2em}.letter-heart{font-size:24px;color:var(--rose)}.salute{font-size:23px;margin-bottom:18px}.letter-body{font-size:15px;line-height:2.05;letter-spacing:.025em}.letter-body p{margin:0 0 16px;opacity:0;transform:translateY(8px);transition:opacity .9s,transform .9s}.letter-body p.revealed{opacity:1;transform:none}.letter-body strong{font-weight:normal;color:#b0446c}.signature{text-align:right;font-size:20px;margin-top:18px;opacity:0;transition:opacity 1s}.signature.revealed{opacity:1}.letter .actions{margin-top:20px}.letter-caption{text-align:center;margin:14px 0 0;color:var(--muted);font-size:10px}.wishes{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;max-width:800px;margin:30px auto}.wish{padding:28px 18px;border:1px solid #fff;border-radius:100px 100px 20px 20px;background:#fff6f5b5;text-align:center;box-shadow:0 15px 45px #a3527015;animation:enter 1s both}.wish:nth-child(2){animation-delay:.3s}.wish:nth-child(3){animation-delay:.6s}.wish .heart{font-size:40px;display:block;margin:10px 0 22px;color:#ce618c;animation:pulse 2.4s infinite}.wish:nth-child(2) .heart{animation-delay:.5s}.wish h3{font-weight:normal;font-size:21px}.wish p{font-size:13px;color:var(--muted);line-height:1.9}.hug-area{min-height:148px;display:flex;align-items:center;justify-content:center;gap:16px;flex-direction:column}.bears{width:150px;height:95px}.hug-message{font-size:14px;margin:0;color:var(--rose)}
.finale{max-width:830px;text-align:center;margin:auto;padding:35px 20px 30px}.big-heart{position:relative;width:180px;height:150px;margin:10px auto 30px}.big-heart svg{width:100%;height:100%;filter:drop-shadow(0 15px 23px #db548a44);animation:pulse 2.8s infinite}.finale .title{font-size:clamp(34px,5vw,58px)}.finale .promise{font-size:19px;line-height:2;color:#98506a}.final-sign{font-size:25px;margin:28px 0;color:var(--rose)}.badge{display:inline-block;border:1px solid #d99eaf;padding:7px 15px;border-radius:30px;font-size:11px;color:var(--muted);letter-spacing:.08em}
footer{position:relative;z-index:4;max-width:990px;margin:0 auto;padding:0 30px 28px;text-align:center}.steps{display:flex;align-items:center;justify-content:center;gap:14px;margin-bottom:15px}.step{border:0;background:transparent;padding:8px 2px;font-size:11px;color:#a77989;position:relative}.step.active{color:#a73161}.step.active:after{content:'';position:absolute;width:4px;height:4px;background:#b14472;border-radius:50%;bottom:0;left:calc(50% - 2px)}.step:disabled{opacity:.6}.line-between{height:1px;width:22px;background:#d4a4b4}.footer-note{font-size:10px;color:#a97788;letter-spacing:.06em}.toast{position:fixed;bottom:34px;left:50%;transform:translate(-50%,20px);opacity:0;z-index:20;background:#fff8faef;border:1px solid #dfa4ba;border-radius:50px;padding:14px 24px;box-shadow:0 8px 30px #9c477733;font-size:14px;transition:opacity .3s,transform .3s;max-width:90vw;text-align:center;pointer-events:none}.toast.show{opacity:1;transform:translate(-50%,0)}
@media(min-width:850px){body{display:flex;flex-direction:column}main{width:100%;flex:1}footer{width:100%}}
@media(max-width:650px){.frame{inset:9px;border-radius:16px}header{padding:25px 24px 8px}.brand strong{font-size:10px;letter-spacing:.14em;white-space:nowrap}.brand{font-size:9px}.tool{font-size:10px;padding:8px 10px}.tools{gap:5px}main{padding:18px 23px 25px}.cover{padding-top:26px}.cover .title{font-size:42px}.envelope{width:270px;height:180px;margin:38px auto 34px}.paper{padding:27px 24px}.hero{grid-template-columns:1fr;gap:4px}.hero-copy{text-align:center;padding:0}.hero-copy h2{font-size:21px}.solar-title{font-size:85px;margin-bottom:5px}.divider{margin:18px auto}.illustration{height:250px}.moon{width:210px;height:210px}.autumn-art{max-width:270px}.dedication{margin-top:15px}.handnote{bottom:-3px;font-size:14px}.cards{grid-template-columns:1fr;gap:13px}.season-card{padding:22px;display:grid;grid-template-columns:88px 1fr;gap:0 16px}.card-art{grid-column:1;grid-row:1/5;height:120px;margin:0;align-self:center}.card-art svg{width:90px}.card-num,.season-card h3,.season-card p{grid-column:2}.season-card h3{font-size:23px;margin:7px 0}.season-card p{font-size:12px}.season-card .romance{margin-top:10px;padding-top:10px;font-size:12px}.letter{padding:30px 26px}.letter-body{font-size:14px;line-height:2}.salute{font-size:21px}.letter-head .eyebrow{font-size:9px}.signature{font-size:17px}.wishes{gap:9px}.wish{padding:17px 9px}.wish .heart{font-size:28px;margin-bottom:14px}.wish h3{font-size:17px}.wish p{font-size:11px}.finale{padding:35px 0 25px}.finale .promise{font-size:16px}.final-sign{font-size:21px}.steps{gap:7px}.line-between{width:12px}.step{font-size:10px}.primary{font-size:13px;padding:13px 23px}.ghost{font-size:12px}footer{padding:0 20px 23px}.section-head .subtitle{font-size:13px}}
@media(max-width:360px){header{flex-wrap:wrap;gap:8px}.brand{width:100%}.tools{margin-left:auto}.cover .title{font-size:36px}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important}.letter-body p{transition:none}}
</style>
</head>
<body>
<div class="ambient" aria-hidden="true"><div class="orb"></div><div class="orb"></div><div class="orb"></div></div>
<canvas id="sky" aria-hidden="true"></canvas><div class="frame" aria-hidden="true"></div><canvas id="spark" aria-hidden="true"></canvas>
<header><div class="brand"><strong>A LETTER IN AUTUMN</strong>寒露 · 一封只给你的情书</div><div class="tools"><button id="music" class="tool" aria-pressed="false">♫ 音乐关</button><button id="pause" class="tool hidden" aria-pressed="false">Ⅱ 暂停翻页</button></div></header>
<main>
<section class="scene active" id="s0" aria-label="打开情书">
<div class="cover" id="cover"><span class="eyebrow">FOR <span data-name></span> · WITH LOVE</span><h1 class="title">秋天寄来一封信</h1><p class="subtitle">给我最喜欢的小朋友，<br>这里藏着一份暖暖的想念。</p>
<div class="envelope" aria-hidden="true"><svg viewBox="0 0 320 213"><defs><linearGradient id="env" x2="1" y2="1"><stop stop-color="#ffe6eb"/><stop offset="1" stop-color="#edb3c9"/></linearGradient></defs><rect x="4" y="8" width="312" height="198" rx="12" fill="url(#env)" stroke="#d99cb2"/><path d="M5 201L160 89 315 201" fill="#f8cad9" stroke="#d99cb2"/><path d="M5 14L160 135 315 14" fill="#ffedf0" stroke="#d99cb2"/><path d="M20 28L160 135 300 28" fill="none" stroke="#d5ac85" stroke-dasharray="3 5"/><g class="seal"><circle cx="160" cy="125" r="28" fill="#c85682"/><circle cx="160" cy="125" r="23" fill="none" stroke="#f5bed1"/><path d="M160 137C139 125 144 108 155 114L160 119 165 114C177 107 182 125 160 137" fill="#ffe9ed"/></g><path d="M0 185Q-12 153 12 143M320 165Q337 133 320 123" fill="none" stroke="#d0a06b" stroke-width="2"/><text x="241" y="180" fill="#b86e8c" font-size="12" font-family="serif">WITH LOVE</text></svg></div>
<div class="stamp">一份秋日限定的偏爱</div><div class="actions"><button class="primary" id="open">拆开这份温柔 ♡</button></div><p class="note cover-tip">点一下拆信，听见秋天，也听见我的心意</p></div>
</section>
<section class="scene" id="s1" aria-label="寒露微凉你在心上"><div class="paper hero"><div class="hero-copy"><span class="eyebrow">THE SEASON OF TENDERNESS</span><h1 class="solar-title">寒露</h1><div class="divider"></div><h2 class="serif">寒露微凉，<br>你在心上。</h2><p class="subtitle">秋风把露珠吹凉了，<br>我想把你的手捂暖。</p><p class="dedication">TO <span data-name></span> · FROM <span data-sender></span></p></div><div class="illustration" aria-hidden="true"><div class="moon"></div><svg class="autumn-art" viewBox="0 0 360 360"><path d="M75 340Q160 230 188 123M123 267Q95 211 59 193M159 209Q230 212 272 175M185 142Q237 113 266 71" fill="none" stroke="#ac9873" stroke-width="3"/><path d="M128 273Q44 274 49 203Q110 211 128 273" fill="#edb6be"/><path d="M164 211Q248 234 277 170Q206 164 164 211" fill="#d7ac88"/><path d="M188 145Q263 145 267 70Q209 87 188 145" fill="#e9c59a"/><path d="M184 142Q122 139 134 77Q177 92 184 142" fill="#f4c6cf"/><g class="flower-art" data-x="103" data-y="171" data-size="65"></g><g class="flower-art" data-x="247" data-y="264" data-size="56"></g><g class="flower-art" data-x="240" data-y="110" data-size="32"></g><path d="M169 73C149 106 150 120 169 121C188 120 189 106 169 73" fill="#fff9ff" stroke="#d5a8bf"/><circle cx="164" cy="108" r="4" fill="white"/><path d="M40 118Q54 105 68 119Q81 105 94 115M225 42Q237 29 250 39Q262 27 276 36" fill="none" stroke="#b58191" stroke-width="2"/><g fill="#c39b69"><path d="M307 199l3 8 8 3-8 3-3 8-3-8-8-3 8-3z"/><path d="M72 62l2 6 6 2-6 2-2 6-2-6-6-2 6-2z"/></g></svg><span class="tiny-heart">♡</span><span class="handnote serif">把秋天的温柔，送给你</span></div></div><div class="actions"><button class="ghost" data-next>看看秋天的小秘密 →</button></div></section>
<section class="scene" id="s2" aria-label="寒露小知识"><div class="section-head"><span class="eyebrow">THREE LITTLE AUTUMN NOTES</span><h2 class="title">秋意渐浓，牵挂也渐浓</h2><p class="subtitle">借三个寒露的意象，偷偷说三句想你。</p></div><div class="cards">
<article class="season-card"><div class="card-art" aria-hidden="true"><svg viewBox="0 0 130 120"><path d="M65 10C27 61 21 98 65 106C110 98 103 61 65 10" fill="#f7dbe9" stroke="#cf9db4"/><path d="M55 39Q30 70 42 84" fill="none" stroke="white" stroke-width="6" stroke-linecap="round"/><circle cx="80" cy="87" r="5" fill="#fff9fd"/><path d="M95 18l3 8 8 3-8 3-3 8-3-8-8-3 8-3z" fill="#c89d65"/></svg></div><span class="card-num">01 / COOL DEW</span><h3 class="serif">露凝秋意</h3><p>寒露时节，天气由凉爽向寒冷过渡，露水也添了凉意。</p><p class="romance">所以今天的第一句想念，是：<br>记得添衣。</p></article>
<article class="season-card"><div class="card-art" aria-hidden="true"><svg viewBox="0 0 130 120"><circle cx="65" cy="59" r="42" fill="#ffe7d9"/><path d="M15 48Q32 30 49 49Q65 31 81 45M52 72Q66 54 80 68Q95 49 114 58M66 24Q76 13 87 23Q97 12 108 20" fill="none" stroke="#ad7388" stroke-width="3" stroke-linecap="round"/><path d="M20 96Q67 84 115 97" fill="none" stroke="#d2b599"/></svg></div><span class="card-num">02 / WILD GEESE</span><h3 class="serif">雁赴远方</h3><p>秋雁向南，带着季节的消息，也带来深秋的问候。</p><p class="romance">而我的牵挂，<br>始终朝着你。</p></article>
<article class="season-card"><div class="card-art"><button class="flower-button" aria-label="点菊花，收下一句悄悄话"><svg viewBox="0 0 130 120"><path d="M63 100L65 66M63 91Q33 91 34 71Q60 72 63 91" fill="#b7be9e" stroke="#99a17f"/><g class="flower-art" data-x="67" data-y="48" data-size="43"></g></svg></button></div><span class="card-num">03 / CHRYSANTHEMUM</span><h3 class="serif">菊开清秋</h3><p>菊花在秋凉中绽放，为渐冷的季节添上一抹明亮。</p><p class="romance">愿你的笑容，<br>也把这个秋天照得亮亮的。</p></article>
</div><p class="source">节气知识参考：中国农业博物馆《寒露》 · <a href="https://jgs.agri.gov.cn/detail/zh/4315.html" target="_blank" rel="noopener noreferrer">了解更多</a><br>画面中的粉色，是<span data-sender></span>为<span data-name></span>调的浪漫滤镜。</p><div class="actions"><button class="ghost" data-next>还有一封信，想读给你听 →</button></div></section>
<section class="scene" id="s3" aria-label="小周写给陌陌的情书"><div class="paper letter"><div class="letter-head"><span class="eyebrow">A LITTLE LOVE, LINE BY LINE</span><span class="letter-heart">♡</span></div><div class="salute serif">亲爱的<span data-name></span>：</div><div class="letter-body" id="letter-body">
<p>寒露到了，秋天又凉了一点，<br>想抱抱你的心，也更认真了一点。</p>
<p>清晨出门的时候，记得多穿一件外套；<br>晚上休息的时候，记得把被子盖好。<br>别让小脚丫偷偷挨冻，<br>也别让忙碌把你的好心情弄丢。</p>
<p>愿你这个秋天，<br>有热乎乎的饭，有甜甜的梦，<br>有喜欢的小惊喜，<br>也有我一直放在心上的惦记。</p>
<p>如果秋风有点凉，就把这封信当作一个抱抱。<br>等见到你，再补上一个真正的。</p>
<p><strong>愿你身上有暖意，眼里有星光，心里有欢喜。<br>寒露快乐，我最喜欢的小朋友。</strong></p>
</div><div class="signature serif" id="signature">—— 想把你捂暖的<span data-sender></span> ♡</div><div class="actions"><button class="ghost" id="reveal">展开整封信 ♡</button><button class="ghost" data-next>收下我的三个小愿望 →</button></div></div><p class="letter-caption">文字会慢慢出现；想多读一会儿，可以点右上角“暂停翻页”。</p></section>
<section class="scene" id="s4" aria-label="三个小愿望"><div class="section-head"><span class="eyebrow">MY THREE WISHES FOR YOU</span><h2 class="title">这个秋天，愿你……</h2><p class="subtitle">每一个小愿望，都有你的名字。</p></div><div class="wishes"><article class="wish"><span class="heart" aria-hidden="true">♥</span><h3 class="serif">暖暖的</h3><p>有热乎乎的饭<br>有软绵绵的被子<br>还有我的抱抱</p></article><article class="wish"><span class="heart" aria-hidden="true">♥</span><h3 class="serif">甜甜的</h3><p>有喜欢的小惊喜<br>有轻松的好心情<br>每天都笑一笑</p></article><article class="wish"><span class="heart" aria-hidden="true">♥</span><h3 class="serif">被爱着</h3><p>有人认真听你说话<br>有人惦记你的冷暖<br>那个人，就是我</p></article></div><div class="actions"><button class="primary" id="hug">收下小周的抱抱 ♡</button><button class="ghost" data-next>最后，还有一句话 →</button></div><div class="hug-area" id="hug-area" aria-live="polite"></div></section>
<section class="scene" id="s5" aria-label="寒露祝福"><div class="finale"><span class="eyebrow">YOU ARE MY FAVORITE SEASON</span><div class="big-heart" aria-hidden="true"><svg viewBox="0 0 180 150"><defs><linearGradient id="heart-gradient" x2=".6" y2="1"><stop stop-color="#f293b6"/><stop offset="1" stop-color="#c44c80"/></linearGradient></defs><path d="M90 138C-14 75 4 5 52 12C71 13 85 28 90 36C103 9 146 0 167 31C204 83 123 121 90 138" fill="url(#heart-gradient)"/><path d="M25 48Q28 23 53 25" stroke="#ffe3ed" stroke-width="5" fill="none" stroke-linecap="round"/><path d="M90 110C37 76 36 45 62 43C78 42 85 52 90 60C103 34 141 39 142 65C143 84 113 98 90 110" fill="none" stroke="#ffd8e8" stroke-width="1"/></svg></div><h2 class="title">寒露快乐，<span data-name></span>。</h2><p class="promise serif">天气会变凉，<br><span data-sender></span>对你的喜欢，一直很热烈。</p><div class="final-sign serif">♡ 最喜欢你 ♡</div><span class="badge">这份偏爱，长期有效</span><div class="actions"><button class="primary" id="fireworks">再放一场爱心烟花 ✦</button><button class="ghost" id="restart">再看一遍 ↺</button></div><p class="note" style="margin-top:23px">点击空白处，也有小小的心动。<br>愿今晚的你，带着甜甜的心情入梦。</p></div></section>
</main>
<footer><nav class="steps" aria-label="情书章节"><button class="step active" data-scene="0">来信</button><span class="line-between"></span><button class="step" data-scene="1" disabled>寒露</button><span class="line-between"></span><button class="step" data-scene="2" disabled>秋意</button><span class="line-between"></span><button class="step" data-scene="3" disabled>情书</button><span class="line-between"></span><button class="step" data-scene="4" disabled>心愿</button><span class="line-between"></span><button class="step" data-scene="5" disabled>喜欢你</button></nav><div class="footer-note">一封秋日情书 · <span data-sender></span>写给<span data-name></span> · ♡</div></footer>
<div class="toast" id="toast" role="status" aria-live="polite"></div>
<script>
'use strict';
const CONFIG=__CONFIG__;
document.querySelectorAll('[data-name]').forEach(e=>e.textContent=CONFIG.name);
document.querySelectorAll('[data-sender]').forEach(e=>e.textContent=CONFIG.sender);
document.getElementById('hug').textContent='收下'+CONFIG.sender+'的抱抱 ♡';
document.title='寒露微凉，'+CONFIG.name+'在心上 · '+CONFIG.sender+'的情书';
const NS='http://www.w3.org/2000/svg';
document.querySelectorAll('.flower-art').forEach(g=>{const x=+g.dataset.x,y=+g.dataset.y,s=+g.dataset.size;for(let ring=0;ring<3;ring++){let n=ring===0?22:18;for(let i=0;i<n;i++){let p=document.createElementNS(NS,'ellipse');let length=s*(1-ring*.22);p.setAttribute('cx',x);p.setAttribute('cy',y-length*.47);p.setAttribute('rx',s*(.095+ring*.014));p.setAttribute('ry',length*.49);p.setAttribute('fill',['#e79aac','#f4b9c5','#ffd7d4'][ring]);p.setAttribute('stroke','#fff1e6');p.setAttribute('stroke-width','.55');p.setAttribute('transform','rotate('+(i*360/n+ring*9)+' '+x+' '+y+')');g.appendChild(p)}}let c=document.createElementNS(NS,'circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r',s*.13);c.setAttribute('fill','#d6b36f');g.appendChild(c)});
const ambience=document.querySelector('.ambient');for(let i=0;i<28;i++){const star=document.createElement('span');star.className='twinkle';star.textContent=i%3===0?'✧':'✦';star.style.cssText='left:'+Math.random()*100+'%;top:'+Math.random()*100+'%;animation-delay:-'+Math.random()*5+'s;font-size:'+(7+Math.random()*9)+'px';ambience.appendChild(star)}for(let i=0;i<12;i++){const d=document.createElement('span');d.className='dewdrop';d.style.cssText='left:'+Math.random()*100+'%;top:'+Math.random()*100+'%;animation-delay:-'+Math.random()*5+'s';ambience.appendChild(d)}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let current=0,opened=false,transitioning=false,paused=false,elapsed=0,letterElapsed=0,revealed=0;
const durations=[0,0,18,32,16,0];
const scenes=[...document.querySelectorAll('.scene')],steps=[...document.querySelectorAll('.step')];
function showScene(n){if(!opened&&n>0)return;current=n;elapsed=0;if(n===0)document.getElementById('cover').classList.remove('opening');scenes.forEach((s,i)=>s.classList.toggle('active',i===n));steps.forEach((s,i)=>s.classList.toggle('active',i===n));window.scrollTo({top:0,behavior:'instant'});if(n===3){letterElapsed=0;revealed=0;document.querySelectorAll('#letter-body p,#signature').forEach(e=>e.classList.remove('revealed'));document.getElementById('reveal').classList.remove('hidden');if(reduced)revealAll()}if(n===5)fireworkShow();document.getElementById('pause').classList.toggle('hidden',n===0||n===5)}
function revealParagraphs(count){const ps=[...document.querySelectorAll('#letter-body p')];ps.forEach((p,i)=>{if(i<count)p.classList.add('revealed')});if(count>=ps.length){document.getElementById('signature').classList.add('revealed');document.getElementById('reveal').classList.add('hidden')}revealed=count}
function revealAll(){revealParagraphs(5)}
document.getElementById('reveal').onclick=revealAll;
document.getElementById('open').onclick=()=>{if(transitioning)return;transitioning=true;opened=true;musicOn();document.getElementById('cover').classList.add('opening');burst(innerWidth/2,innerHeight*.5,36);setTimeout(()=>{steps.forEach(s=>s.disabled=false);showScene(1);transitioning=false},reduced?0:850)};
document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{const isAutumnSecret=current===1;showScene(Math.min(5,current+1));if(isAutumnSecret)startNarration()});
steps.forEach(s=>s.onclick=()=>{if(transitioning)return;showScene(+s.dataset.scene)});
const pauseButton=document.getElementById('pause');pauseButton.onclick=()=>{paused=!paused;pauseButton.textContent=paused?'▶ 继续翻页':'Ⅱ 暂停翻页';pauseButton.setAttribute('aria-pressed',String(paused));if(paused)toast('慢慢看，我的心意不会跑走 ♡')};
document.getElementById('restart').onclick=()=>{paused=false;pauseButton.textContent='Ⅱ 暂停翻页';pauseButton.setAttribute('aria-pressed','false');document.getElementById('hug-area').replaceChildren();showScene(1)};
let toastTimer;function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3100)}
const whispers=['今天也要开心呀 ♡','小脚丫记得保暖 ♡','又偷偷想你了 ♡','想和你一起，把秋天过得暖暖的 ♡'];let whisperIndex=0;document.querySelector('.flower-button').onclick=e=>{toast(whispers[whisperIndex++%whispers.length]);let r=e.currentTarget.getBoundingClientRect();burst(r.x+r.width/2,r.y+r.height/2,22)};
document.getElementById('hug').onclick=()=>{let area=document.getElementById('hug-area');area.innerHTML='<svg class="bears" viewBox="0 0 170 108" aria-label="两只小熊抱在一起"><g fill="#d4a987" stroke="#b68b73" stroke-width="1.5"><circle cx="37" cy="26" r="13"/><circle cx="81" cy="26" r="13"/><ellipse cx="61" cy="77" rx="29" ry="28"/><circle cx="59" cy="44" r="29"/></g><g fill="#f0cbd3" stroke="#ca9aaa" stroke-width="1.5"><circle cx="97" cy="26" r="13"/><circle cx="141" cy="26" r="13"/><ellipse cx="115" cy="77" rx="29" ry="28"/><circle cx="119" cy="44" r="29"/></g><g fill="#725246"><circle cx="49" cy="43" r="2.5"/><circle cx="67" cy="43" r="2.5"/><circle cx="110" cy="43" r="2.5"/><circle cx="128" cy="43" r="2.5"/></g><g fill="#fff2e4"><ellipse cx="59" cy="54" rx="10" ry="7"/><ellipse cx="119" cy="54" rx="10" ry="7"/></g><path d="M55 51L63 51 59 55zM115 51L123 51 119 55z" fill="#725246"/><path d="M56 75Q86 102 121 76" fill="none" stroke="#d4a987" stroke-width="16" stroke-linecap="round"/><path d="M89 87C60 71 70 54 83 62L89 68 95 62C110 54 119 72 89 87" fill="#d96991"/><g fill="#e9a0ac" opacity=".8"><ellipse cx="41" cy="53" rx="6" ry="3"/><ellipse cx="135" cy="53" rx="6" ry="3"/></g></svg><p class="hug-message">抱抱已送达，记得签收 ♡</p>';toast(CONFIG.sender+'的抱抱，专属于'+CONFIG.name+' ♡');burst(innerWidth/2,innerHeight*.65,45);elapsed=0};
// 纯浏览器合成的八音盒：无外部音频，无联网请求。
let audioCtx=null,musicEnabled=false,musicTimer=null,noteIndex=0;
const melody=[523.25,659.25,783.99,659.25,587.33,698.46,880,698.46,659.25,783.99,1046.5,987.77,880,783.99,659.25,587.33,523.25,659.25,783.99,1046.5,987.77,783.99,698.46,659.25];
function chime(freq,time,volume){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime(volume,time+.012);g.gain.exponentialRampToValueAtTime(.0001,time+1.6);o.connect(g);g.connect(audioCtx.destination);o.start(time);o.stop(time+1.7)}
function playNote(){if(narrating||!musicEnabled||document.hidden||!audioCtx||audioCtx.state!=='running')return;const f=melody[noteIndex%melody.length],t=audioCtx.currentTime;chime(f,t,.045);chime(f*2,t,.008);if(noteIndex%4===0)chime([130.81,174.61,164.81,146.83][Math.floor(noteIndex/4)%4],t,.025);noteIndex++}
function updateMusicButton(){const button=document.getElementById('music');button.textContent=narrating?(musicEnabled?'♫ 语录播放中':'♫ 语录已静音'):(musicEnabled?'♫ 音乐开':'♫ 音乐关');button.setAttribute('aria-pressed',String(musicEnabled))}
async function musicOn(){musicEnabled=true;if(narrating){narration.muted=false;updateMusicButton();return}try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){musicEnabled=false;updateMusicButton();toast('这个浏览器不支持音乐，心意一样送达 ♡');return}if(!audioCtx)audioCtx=new Audio();if(!document.hidden)await audioCtx.resume();if(narrating||!musicEnabled){if(narrating)audioCtx.suspend().catch(()=>{});return}clearInterval(musicTimer);musicTimer=setInterval(playNote,440);playNote();updateMusicButton()}catch(e){musicEnabled=false;updateMusicButton();toast('音乐暂时没响，点右上角可以再试一次 ♡')}}
function musicOff(){musicEnabled=false;clearInterval(musicTimer);if(narrating)narration.muted=true;if(audioCtx)audioCtx.suspend().catch(()=>{});updateMusicButton()}
document.getElementById('music').onclick=()=>musicEnabled?musicOff():musicOn();
document.addEventListener('visibilitychange',()=>{if(!audioCtx)return;if(document.hidden||narrating)audioCtx.suspend().catch(()=>{});else if(musicEnabled)audioCtx.resume().catch(()=>{})});
// MP3 内嵌在单文件网页中。点击“小秘密”才播放，结束后恢复八音盒。
const narration=new Audio('data:audio/mpeg;base64,__NARRATION__');
narration.preload='metadata';narration.loop=false;
let narrating=false;
async function startNarration(){if(narrating)return;narrating=true;musicEnabled=true;narration.muted=false;narration.currentTime=0;clearInterval(musicTimer);if(audioCtx)audioCtx.suspend().catch(()=>{});updateMusicButton();try{await narration.play()}catch(e){finishNarration();toast('语录暂时没响，请再点一次“看看秋天的小秘密” ♡')}}
function finishNarration(){if(!narrating)return;narrating=false;elapsed=0;updateMusicButton();if(musicEnabled)musicOn()}
narration.addEventListener('ended',finishNarration);
narration.addEventListener('error',()=>{const wasPlaying=narrating;finishNarration();if(wasPlaying)toast('语录播放遇到问题，已切回背景音乐 ♡')});
// 花瓣与心形烟花分别绘制，不阻挡文字、按钮或手机触摸。
const sky=document.getElementById('sky'),spark=document.getElementById('spark'),ctx=sky.getContext('2d'),fx=spark.getContext('2d');let W=innerWidth,H=innerHeight,dpr=1;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);[sky,spark].forEach(c=>{c.width=W*dpr;c.height=H*dpr});ctx.setTransform(dpr,0,0,dpr,0,0);fx.setTransform(dpr,0,0,dpr,0,0)}window.addEventListener('resize',resize);resize();
const petals=Array.from({length:reduced?0:34},()=>({x:Math.random()*W,y:Math.random()*H,s:4+Math.random()*6,v:12+Math.random()*17,phase:Math.random()*6.28,a:Math.random()*6.28}));
const particles=[];const colors=['#d85b91','#ed91b2','#bb779d','#c7a15d','#efb8cb'];
function heart(c,x,y,s,color,alpha,rotation){c.save();c.translate(x,y);c.rotate(rotation||0);c.globalAlpha=alpha;c.fillStyle=color;c.beginPath();c.moveTo(0,s*.45);c.bezierCurveTo(-s,-s*.2,-s*.5,-s,0,-s*.4);c.bezierCurveTo(s*.5,-s,s,-s*.2,0,s*.45);c.fill();c.restore()}
function burst(x,y,n){for(let i=0;i<(reduced?Math.min(n,8):n);i++){const a=Math.random()*Math.PI*2,v=35+Math.random()*100;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-30,life:1.3+Math.random(),max:2.3,s:3+Math.random()*5,c:colors[i%5],heart:i%3===0})}}
function heartFirework(x,y,scale){const count=reduced?20:100;for(let i=0;i<count;i++){let t=i/count*Math.PI*2,hx=16*Math.pow(Math.sin(t),3),hy=-(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t));particles.push({x,y,vx:hx*scale,vy:hy*scale,life:2.6,max:2.6,s:2.2+Math.random()*2.2,c:colors[i%5],heart:i%9===0})}burst(x,y,12)}
let fireworksTimers=[];function fireworkShow(){fireworksTimers.forEach(clearTimeout);fireworksTimers=[];const positions=[[.5,.38],[.27,.52],[.74,.43]];positions.forEach((p,i)=>fireworksTimers.push(setTimeout(()=>{if(current===5)heartFirework(W*p[0],H*p[1],Math.min(W/110,5))},i*1000)))}
document.getElementById('fireworks').onclick=fireworkShow;
let pointerTime=0;document.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||reduced)return;let now=performance.now();if(now-pointerTime<65)return;pointerTime=now;particles.push({x:e.clientX,y:e.clientY,vx:(Math.random()-.5)*12,vy:-12,life:.65,max:.65,s:2.5,c:'#c79b62',heart:false})});
document.addEventListener('click',e=>{if(e.target.closest('button,a'))return;burst(e.clientX,e.clientY,18)});
let last=performance.now(),lastDraw=0;
function animate(now){const dt=Math.min((now-last)/1000,.08);last=now;if(!document.hidden){if(opened&&!transitioning&&current>0&&current<5&&!paused){elapsed+=dt;if(current===3){letterElapsed+=dt;let n=Math.min(5,1+Math.floor(letterElapsed/4.3));if(n>revealed)revealParagraphs(n)}// 手机阅读较长时，停在当前幕，待滚动到底再自动翻页。
const nearBottom=scrollY+innerHeight>=document.documentElement.scrollHeight-90;if(durations[current]>0&&elapsed>=durations[current]&&nearBottom&&!(current===2&&narrating))showScene(current+1)}
if(now-lastDraw>30){const drawDt=Math.min((now-lastDraw)/1000,.08);lastDraw=now;ctx.clearRect(0,0,W,H);fx.clearRect(0,0,W,H);petals.forEach(p=>{p.y+=p.v*drawDt;p.x+=Math.sin(now/2200+p.phase)*7*drawDt;p.a+=drawDt*.3;if(p.y>H+20){p.y=-20;p.x=Math.random()*W}ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.globalAlpha=.37;ctx.fillStyle='#d889ad';ctx.beginPath();ctx.ellipse(0,0,p.s*.48,p.s,0,0,Math.PI*2);ctx.fill();ctx.restore()});for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=drawDt;if(p.life<=0){particles.splice(i,1);continue}p.x+=p.vx*drawDt;p.y+=p.vy*drawDt;p.vx*=Math.pow(.985,drawDt*30);p.vy+=13*drawDt;let a=Math.min(1,p.life/.7);if(p.heart)heart(fx,p.x,p.y,p.s,p.c,a,0);else{fx.globalAlpha=a;fx.fillStyle=p.c;fx.beginPath();fx.arc(p.x,p.y,p.s*.55,0,Math.PI*2);fx.fill()}}fx.globalAlpha=1}}
requestAnimationFrame(animate)}requestAnimationFrame(animate);
</script>
</body></html>'''


def generate(name, sender, destination, audio_path=None):
    """嵌入安全的个性化配置，保存可直接打开的单文件 HTML。"""
    config = json.dumps({'name': name, 'sender': sender}, ensure_ascii=False)
    # 防止自定义昵称中的 HTML 字符结束 script 标签。
    config = config.replace('&', '\\u0026').replace('<', '\\u003c').replace('>', '\\u003e')
    config = config.replace('\u2028', '\\u2028').replace('\u2029', '\\u2029')
    audio_path = Path(audio_path) if audio_path is not None else Path(__file__).resolve().with_name('寒露语录.mp3')
    narration = base64.b64encode(audio_path.read_bytes()).decode('ascii')
    destination = Path(destination).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(HTML.replace('__CONFIG__', config).replace('__NARRATION__', narration), encoding='utf-8')
    return destination


def main():
    parser = argparse.ArgumentParser(description='生成粉色系寒露动态情书；仅使用 Python 标准库。')
    parser.add_argument('--name', default='陌陌', help='女朋友的昵称，默认：陌陌')
    parser.add_argument('--sender', default='小周', help='你的署名，默认：小周')
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().with_name('给陌陌的寒露情书.html'), help='保存的 HTML 路径')
    parser.add_argument('--audio', type=Path, default=Path(__file__).resolve().with_name('寒露语录.mp3'), help='点击秋天的小秘密后播放的 MP3，默认读取代码旁的寒露语录.mp3')
    parser.add_argument('--no-open', action='store_true', help='只生成文件，不自动打开浏览器')
    args = parser.parse_args()
    try:
        result = generate(args.name, args.sender, args.output, args.audio)
    except OSError as error:
        parser.error('无法读取音频或保存网页：{}'.format(error))
    print('寒露情书已生成：{}'.format(result))
    print('将这个 HTML 文件发给她，用浏览器打开即可；无需 Python 或网络。')
    if not args.no_open:
        webbrowser.open(result.as_uri())


if __name__ == '__main__':
    main()
